CREATE TABLE BOOKS (
    ID INT NOT NULL IDENTITY(1,1),
    NAME TEXT,
    PDF_FILE TEXT,
    TOTAL_PAGES INT,
    PRIMARY KEY (ID)
);

CREATE TABLE USERS (
    ID INT NOT NULL IDENTITY(1,1),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(255),
    IS_ADMIN BIT,
    FIREBASE_ID VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE GROUPS (
    ID INT NOT NULL,
    ADMIN_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    NAME TEXT,
    PRIMARY KEY (USER_ID, ID),
    CONSTRAINT FK_ADMIN FOREIGN KEY (ADMIN_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE LESSONS (
    ID INT NOT NULL IDENTITY(1,1),
    BOOK_ID INT,
    START_PAGE INT,
    END_PAGE INT,
    NAME TEXT,
    PDF_FILE TEXT,
    GROUP_ID INT,
    PRIMARY KEY (ID),
    CONSTRAINT FK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
    CONSTRAINT FK_GROUP FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID)
);

CREATE TABLE ASSIGNMENTS (
    ID INT NOT NULL IDENTITY(1,1),
    NAME TEXT,
    LESSON_ID INT,
    GROUP_ID INT,
    DUE_DATE DATETIME,
    START_DATE DATETIME,
    END_DATE DATETIME,
    TIME_TO_COMPLETE INT,
    AVAILABLE bit,
    NOTES TEXT,
    PRIMARY KEY (ID),
    CONSTRAINT FK_LESSON FOREIGN KEY (LESSON_ID) REFERENCES LESSONS(ID),
    CONSTRAINT FK_GROUP_ASSIGNMENTS FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID)
);

CREATE TABLE STATUS (
    GROUP_ID INT,
    EMPLOYEE_ID INT,
    ASSIGNMENT_ID INT,
    IS_COMPLETE BIT,
    PRIMARY KEY(GROUP_ID, EMPLOYEE_ID, ASSIGNMENT_ID),
    CONSTRAINT FK_GROUP_STATUS FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID),
    CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES ASSIGNMENTS(ID)
);
